# Very similar file to the deployment one, but this

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app # it's possible to group even just by one selector
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # it's possible to specify multiple ports if necessary
  type: LoadBalancer